language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  irc:
    channels:
      - "chat.freenode.net##add"
    on_success: change
    on_failure: always